/**
 * Starter questions for the empty state.
 *
 * The reference product opens a notebook with tappable questions instead of a
 * paragraph, so this replaces a block of explanatory prose that was more honest
 * about grounding and read as a terms-of-service notice on first load.
 *
 * These are derived from source *names* plus each source's numeric-density flag.
 * That is a deliberate limit and worth being explicit about: the reference
 * product reads the notebook to write its suggestions, which means a model call
 * on every load, costing money and latency before the user has typed anything.
 * Names and the flag are already in memory from `/api/status`, so this costs
 * nothing and cannot fail. If the suggestions turn out to be too generic to be
 * worth having, the fix is an endpoint that samples a few chunks and asks for
 * questions - not a longer list of hardcoded strings.
 */

/** Spreadsheet kinds, where a figures question is apt whatever the chunk stats say. */
const TABLE_KINDS = new Set(["csv", "xls", "xlsx", "tsv"]);

/** Extensions and separators that make a filename a bad question subject. */
const NOISE = /\.(pdf|docx?|txt|md|csv|pptx?|xlsx?|html?|epub)$/i;

/**
 * Filenames this app generated itself, rather than ones a person typed.
 *
 * Uploads are stored under a UUID (store.py writes `<uuid>.<ext>`), and a
 * notebook built through the API or a script can therefore hold sources named
 * "2a7062e3acce425790117aba9bdc1167.pdf". Turning that into a question produces
 * "What are the key points about 2a7062e3acce425790117aba9bdc1167?" - which
 * retrieves nothing, so the app refuses an answer to a question it invented
 * one click earlier. The length filter does not catch it, because a UUID stem is
 * 32 characters and sits comfortably inside the readable range.
 *
 * The test is deliberately narrow: **hex characters only, and long**. Two weaker
 * signals were tried and rejected. "No vowels" fails because `deadbeef` contains
 * `a` and `e`. "Digit-dense" fails because `iso-27001-controls` is as
 * digit-heavy as a hash while being an entirely real name. Requiring the whole
 * stem to be hex and at least 8 characters catches UUIDs, content hashes and
 * base32 names, and passes every real filename tried against it.
 *
 * The boundary this leaves: a short hex token such as `f00d.pdf` is still used
 * as a subject. That costs one weak suggestion rather than losing a real name,
 * and no longer token is generated by the app itself.
 */
function looksGenerated(name) {
  const stem = name.replace(NOISE, "");
  if (!stem) return true;
  return /^[0-9a-f]{8,}$/i.test(stem.replace(/[\s_-]/g, ""));
}

/**
 * A human-readable subject from a filename: "q3-returns-policy_v2.pdf" becomes
 * "returns policy". Deliberately lossy - it only has to read well in a
 * sentence, and the retriever resolves the real topic from the query.
 *
 * Returns "" for a generated name, which is what sends `suggestionsFor` down
 * its generic-but-answerable path.
 */
export function subjectFromName(name) {
  if (!name) return "";
  if (looksGenerated(name)) return "";
  return name
    .replace(NOISE, "")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Questions to offer for a notebook, best-first.
 *
 * `sources` is the `/api/status` source list. Returns an empty array when
 * there is nothing to ask about yet, because suggesting questions for an empty
 * notebook produces four refusals - the app refuses when retrieval finds
 * nothing, and that is the first impression we would be giving.
 */
export function suggestionsFor(sources) {
  if (!sources || !sources.length) return [];

  const names = sources.map((s) => subjectFromName(s.name)).filter(Boolean);
  // A question about a specific document beats a generic one when the names are
  // short enough to stay readable; very long filenames make for absurd prose.
  const usable = names.filter((n) => n.length > 2 && n.length <= 48);
  const subject = usable[0] || "";
  // Two signals, because neither alone is right.
  //
  // `numeric` is the count of numeric-dense chunks, which catches logs and bare
  // data dumps but almost never a spreadsheet: the CSV parser reshapes a table
  // into `Label: Value` lines, and "Revenue: 12000" is 5 digits in 13
  // characters, well under the 0.5 density `parsers.is_numeric_heavy` asks for.
  // A 40-row revenue table and a one-paragraph memo both report 0.
  //
  // The source kind catches what the flag misses. A spreadsheet is figures by
  // construction, so the question is worth asking there without measuring.
  //
  // Prose that merely mentions "30 days" triggers neither, which is the intended
  // conservatism: a numbers question that cannot be answered teaches the user
  // that this app invents figures.
  const hasNumbers =
    sources.some((s) => (s.numeric || 0) > 0) ||
    sources.some((s) => TABLE_KINDS.has(String(s.kind || "").toLowerCase()));

  const out = [];
  if (subject) {
    out.push(`What are the key points about ${subject}?`);
    out.push(`Summarise ${subject} in a few sentences`);
  } else {
    // No usable filename, so nothing can be named without producing a
    // nonsensical question ("the key points about r2?"). Fall back to questions
    // that are generic by wording rather than by accident, and that still do the
    // job - a summary of the notebook is the one thing always worth offering.
    out.push("Summarise these sources in a few sentences");
    out.push("What are the key points across these sources?");
  }
  // Only offered when the corpus actually contains figures. A numbers question
  // against a prose-only corpus teaches the user that this app invents figures.
  if (hasNumbers) {
    out.push("What figures and dates does this mention?");
  }
  if (usable.length > 1) {
    out.push(`How does ${usable[1]} relate to ${usable[0]}?`);
  }
  return out;
}

/**
 * The one entry that is not a question about the corpus.
 *
 * "What questions should I be asking about this?" used to sit at the end of the
 * suggestion list like any other, and clicking it sent the text to the model.
 * Retrieval found no passage about how to use the app, the relevance floor
 * refused, and the user got "I could not find anything relevant in the indexed
 * sources" in reply to a question the app itself had written. That is the worst
 * possible first impression: the app proposes a question and then refuses it.
 *
 * So it is handled separately. Clicking it expands the questions above as
 * clickable pills instead of asking anything, which is what the wording
 * promises. It is returned as a flag rather than a string so it cannot be
 * confused with a question again.
 */
export const EXPLORE = "__explore__";

/**
 * Questions to offer for a notebook, best-first, with any trailing "show me
 * more questions" control appended.
 *
 * `sources` is the `/api/status` source list. Returns only `[]` when there is
 * nothing to ask about yet, because suggesting questions for an empty notebook
 * produces four refusals - the app refuses when retrieval finds nothing, and
 * that is the first impression we would be giving.
 */
export function suggestionsWithExplore(sources) {
  const questions = suggestionsFor(sources);
  return questions.length ? [...questions, EXPLORE] : [];
}